# Generated by Django 3.1.5 on 2021-01-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='company',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
